export const categories = [
  {
    name: "sideproject",
    label: "r/sideproject",
    icon: "fas fa-rocket",
    color: { h: 210, s: 100, l: 50 },
    // color: { h: 15, s: 83, l: 47 },
  },
  {
    name: "longDistance",
    label: "r/LongDistance",
    icon: "fas fa-heart",
    color: { h: 330, s: 100, l: 50 },
    // color: { h: 15, s: 83, l: 47 },
  },
  // {
  //   name: "dunderMifflin",
  //   label: "r/DunderMifflin",
  //   icon: "fas fa-briefcase",
  //   color: { h: 150, s: 100, l: 40 },
  //   // color: { h: 15, s: 83, l: 47 },
  // },
  {
    name: "cozyGamers",
    label: "r/CozyGamers",
    icon: "fas fa-couch",
    color: { h: 150, s: 100, l: 40 },
    // color: { h: 15, s: 83, l: 47 },
  },
  {
    name: "general",
    label: "General",
    icon: "fas fa-star",
    color: { h: 551, s: 95, l: 43 }, // Teal
  },
  {
    name: "getToKnowYou",
    label: "Get To Know You",
    icon: "fas fa-user-friends",
    color: { h: 686, s: 95, l: 43 }, // Pink
  },
  {
    name: "forCouples",
    label: "For Couples",
    icon: "fas fa-heart",
    color: { h: 461, s: 95, l: 43 }, // Green
  },
  {
    name: "toAskYourGirlfriend",
    label: "Ask Your Girlfriend",
    icon: "fas fa-female",
    color: { h: 619, s: 95, l: 43 }, // Purple
  },
  {
    name: "toAskYourBoyfriend",
    label: "Ask Your Boyfriend",
    icon: "fas fa-male",
    color: { h: 484, s: 95, l: 43 }, // Yellow-Green
  },
  {
    name: "forKids",
    label: "For Kids",
    icon: "fas fa-child",
    color: { h: 574, s: 95, l: 43 }, // Blue
  },
  {
    name: "work",
    label: "Work",
    icon: "fas fa-briefcase",
    color: { h: 416, s: 95, l: 43 }, // Yellow
  },
  {
    name: "travel",
    label: "Travel",
    icon: "fas fa-plane",
    color: { h: 641, s: 95, l: 43 }, // Indigo
  },
  {
    name: "foodAndDrinks",
    label: "Food And Drinks",
    icon: "fas fa-utensils",
    color: { h: 506, s: 95, l: 43 }, // Pink-Purple
  },
  {
    name: "funny",
    label: "Funny",
    icon: "fas fa-laugh",
    color: { h: 596, s: 95, l: 43 }, // Blue-Purple
  },
  {
    name: "weird",
    label: "Weird",
    icon: "fas fa-flushed",
    color: { h: 371, s: 95, l: 43 }, // Red-Orange
  },
  {
    name: "spicy",
    label: "Spicy",
    icon: "fas fa-pepper-hot",
    color: { h: 349, s: 95, l: 43 }, // Spicy Red (original color)
  },
  {
    name: "adultWouldYouRather",
    label: "Adult Dilemmas",
    icon: "fas fa-question-circle",
    color: { h: 664, s: 95, l: 43 }, // Violet
  },
  {
    name: "christmas",
    label: "Christmas",
    icon: "fas fa-gift",
    color: { h: 439, s: 95, l: 43 }, // Yellow-Orange
  },
  {
    name: "productHunt",
    label: "Product Hunt",
    icon: "fas fa-project-diagram",
    color: { h: 394, s: 95, l: 43 }, // Product Hunt Orange (original color)
  },
];

export const questions = {
  sideproject: [
    { option1: "Launch now", option2: "Perfect later" },
    { option1: "Solo founder", option2: "Co-founder" },
    { option1: "Bootstrap", option2: "Raise funding" },
    { option1: "Web app", option2: "Mobile app" },
    { option1: "Open source", option2: "Proprietary" },
    { option1: "Freemium", option2: "Paid only" },
    { option1: "AI-powered", option2: "Human-powered" },
    { option1: "Niche market", option2: "Mass market" },
    { option1: "Revenue first", option2: "Users first" },
    { option1: "Code from scratch", option2: "Use frameworks" },
    { option1: "Learn new tech", option2: "Stick to what you know" },
    { option1: "Work on weekends", option2: "Work on weeknights" },
    { option1: "Tell friends", option2: "Keep it secret" },
    { option1: "Quit day job", option2: "Side hustle forever" },
    { option1: "Remote team", option2: "In-person team" },
    { option1: "B2B", option2: "B2C" },
    { option1: "Subscription model", option2: "One-time purchase" },
    { option1: "MVP", option2: "Fully-featured v1" },
    { option1: "Social media marketing", option2: "Word of mouth" },
    { option1: "Patent your idea", option2: "Ship fast and iterate" },
    { option1: "Cold emailing", option2: "Content marketing" },
    { option1: "Hackathon project", option2: "Long-term development" },
    { option1: "Solve your own problem", option2: "Market research" },
    { option1: "Design first", option2: "Functionality first" },
    { option1: "Cloud hosting", option2: "Self-hosted" },
    { option1: "General-purpose tool", option2: "Specialized solution" },
    { option1: "Impress investors", option2: "Delight users" },
    { option1: "Growth hacking", option2: "Organic growth" },
    { option1: "Visual builder", option2: "Hand-coded" },
    { option1: "Fast and buggy", option2: "Slow and stable" },
    { option1: "Pivot", option2: "Persevere" },
    { option1: "Reddit for marketing", option2: "Product Hunt launch" },
    { option1: "Blockchain-based", option2: "Traditional tech stack" },
    { option1: "Lean startup", option2: "Detailed business plan" },
    { option1: "Customer support chatbot", option2: "Human support team" },
    { option1: "Ad-supported", option2: "Ad-free premium" },
    { option1: "Mobile-first", option2: "Desktop-first" },
    { option1: "Viral features", option2: "Practical features" },
    { option1: "Gamification", option2: "Straightforward UX" },
    { option1: "Early access program", option2: "Stealth mode" },
    { option1: "Influencer partnerships", option2: "Grassroots community" },
    { option1: "Agile development", option2: "Waterfall method" },
    { option1: "Outsource design", option2: "DIY everything" },
    { option1: "Metrics-driven", option2: "Intuition-driven" },
    { option1: "SAAS", option2: "One-time download" },
    { option1: "Minimal landing page", option2: "Feature-rich website" },
    { option1: "User interviews", option2: "Analytics data" },
    { option1: "Fancy tech stack", option2: "Boring technology" },
    { option1: "CLI tool", option2: "GUI application" },
    { option1: "Indie hacker", option2: "Startup founder" },
  ],
  longDistance: [
    { option1: "Netflix and chill", option2: "Video game date" },
    { option1: "Morning person", option2: "Night owl" },
    { option1: "Surprise gifts", option2: "Planned presents" },
    { option1: "Texting", option2: "Phone calls" },
    { option1: "Beach vacation", option2: "Mountain getaway" },
    { option1: "Romantic comedy", option2: "Action movie" },
    { option1: "Spicy food", option2: "Mild flavors" },
    { option1: "Social butterfly", option2: "Homebody" },
    { option1: "Spontaneous trips", option2: "Planned adventures" },
    { option1: "Early goodbye", option2: "Lingering farewell" },
    { option1: "Silly selfies", option2: "Romantic photos" },
    { option1: "Long letters", option2: "Short, frequent messages" },
    { option1: "Virtual museum tour", option2: "Online cooking class" },
    { option1: "Matching outfits", option2: "Coordinated accessories" },
    { option1: "Outdoor picnic", option2: "Indoor fort building" },
    { option1: "Karaoke night", option2: "Book club" },
    { option1: "Shared playlist", option2: "Personalized mixtape" },
    { option1: "Morning texts", option2: "Goodnight calls" },
    { option1: "Fantasy role-play", option2: "Real-life stories" },
    { option1: "Public displays of affection", option2: "Private intimacy" },
    { option1: "Surprise wake-up call", option2: "Scheduled good morning" },
    { option1: "Hand-written notes", option2: "Digital love notes" },
    { option1: "Virtual double date", option2: "Solo date night" },
    { option1: "Sexy voice messages", option2: "Flirty emojis" },
    { option1: "Talk about the future", option2: "Live in the moment" },
    { option1: "Shared journal", option2: "Individual diaries" },
    { option1: "Virtual workouts", option2: "Cooking together online" },
    { option1: "Countdown calendar", option2: "Surprise visit" },
    { option1: "Online game night", option2: "Movie marathon" },
    { option1: "Long-term goals", option2: "Short-term plans" },
    { option1: "Dirty talk", option2: "Innocent flirting" },
    { option1: "Shared social media", option2: "Private accounts" },
    { option1: "Virtual dance party", option2: "Quiet video chat" },
    { option1: "Naughty photos", option2: "Sweet compliments" },
    {
      option1: "Learn a language together",
      option2: "Pick up a hobby separately",
    },
    { option1: "Plan next meeting", option2: "Reminisce about last one" },
    { option1: "Scheduled intimacy", option2: "Spontaneous sexy time" },
    { option1: "Virtual stargazing", option2: "Online art gallery tour" },
    { option1: "Matching tattoos", option2: "Couple's jewelry" },
    { option1: "Sexting", option2: "Romantic poetry" },
    { option1: "Shared to-do lists", option2: "Independent goals" },
    { option1: "Virtual wine tasting", option2: "Online escape room" },
    { option1: "Couple's app", option2: "Personal messaging" },
    { option1: "Fantasy future home", option2: "Current living spaces" },
    { option1: "Care package", option2: "Digital gift card" },
    { option1: "Read same book", option2: "Watch same TV show" },
    {
      option1: "Celebrate monthly anniversaries",
      option2: "Mark bigger milestones",
    },
    { option1: "Intimate truth or dare", option2: "Deep conversation prompts" },
    { option1: "Joint bucket list", option2: "Personal achievements" },
    { option1: "Sexy costume surprise", option2: "Everyday outfit reveal" },
  ],
  dunderMifflin: [
    { option1: "Jim", option2: "Dwight" },
    { option1: "Dunder Mifflin", option2: "Michael Scott Paper Company" },
    {
      option1: "That's what she said",
      option2: "Beets, bears, Battlestar Galactica",
    },
    { option1: "Pretzel Day", option2: "Beach Day" },
    { option1: "Dundies", option2: "Dundie Mifflin Infinity" },
    { option1: "Threat Level Midnight", option2: "The Client" },
    { option1: "Scranton", option2: "Corporate" },
    { option1: "Chili's", option2: "Poor Richard's" },
    { option1: "Prison Mike", option2: "Date Mike" },
    { option1: "Kevin's famous chili", option2: "Dwight's beet farm" },
    { option1: "Creed's blog", option2: "Ryan's WUPHF.com" },
    { option1: "Flonkerton", option2: "Dunder Ball" },
    { option1: "Asian Jim prank", option2: "Dwight's fire drill" },
    { option1: "Pam's art show", option2: "Michael's improv class" },
    { option1: "Scott's Tots", option2: "Dinner Party" },
    { option1: "Recyclops", option2: "Belsnickel" },
    { option1: "Angela's cats", option2: "Meredith's van" },
    {
      option1: "Kelly's customer service",
      option2: "Dwight's sales techniques",
    },
    { option1: "Phyllis' perfume", option2: "Kevin's M&M jar" },
    { option1: "The Stamford branch", option2: "The Scranton branch" },
    { option1: "Cafe Disco", option2: "The Warehouse" },
    { option1: "Schrute Bucks", option2: "Stanley Nickels" },
    { option1: "Jan's candles", option2: "Ryan's cheese pita" },
    { option1: "Michael's movie script", option2: "Pam's comic book" },
    { option1: "Toby", option2: "The Strangler" },
    { option1: "Diversity Day", option2: "Safety Training Day" },
    { option1: "Booze Cruise", option2: "Benihana Christmas" },
    { option1: "Gabe", option2: "Robert California" },
    { option1: "Dwight's perfect crime", option2: "Jim's greatest pranks" },
    { option1: "The Fun Run", option2: "The Dundies" },
    { option1: "Finer Things Club", option2: "Party Planning Committee" },
    {
      option1: "Michael's World's Best Boss mug",
      option2: "Dwight's bobblehead",
    },
    { option1: "The Nard Dog", option2: "Big Tuna" },
    { option1: "Pam's teapot", option2: "Jim's yearbook photo" },
    { option1: "Kevin's band", option2: "Andy's a cappella group" },
    { option1: "Creed's mung beans", option2: "Dwight's weapons cache" },
    {
      option1: "Meredith's casual friday outfit",
      option2: "Kevin's famous chili recipe",
    },
    { option1: "Dunder Mifflin Infinity website", option2: "WUPHF.com" },
    { option1: "Scranton Strangler trial", option2: "Michael's deposition" },
    { option1: "Pam's coal walk", option2: "Dwight's fire walk" },
    { option1: "Michael's nephews", option2: "Erin's foster brother" },
    { option1: "The annex", option2: "Accounting corner" },
    { option1: "Oscar's origami", option2: "Creed's chess skills" },
    { option1: "Michael's screenplay", option2: "Darryl's children's book" },
    { option1: "Angela's posters", option2: "Kelly's Ryan shrine" },
    { option1: "Dwight's Hay Place", option2: "Kevin's Big Mac idea" },
    { option1: "Creed's fake ID business", option2: "Ryan's shoe company" },
    { option1: "Mega Desk", option2: "Quad Desk" },
    { option1: "Holly", option2: "Chair Model" },
  ],
  cozyGamers: [
    { option1: "Stardew Valley", option2: "Animal Crossing" },
    { option1: "Cozy blanket", option2: "Comfy gaming chair" },
    { option1: "Pixel art", option2: "3D graphics" },
    { option1: "Farming sim", option2: "Life sim" },
    { option1: "Hot cocoa", option2: "Herbal tea" },
    { option1: "Rainy day gaming", option2: "Sunny day gaming" },
    { option1: "Crafting", option2: "Exploring" },
    { option1: "Wholesome NPCs", option2: "Quirky NPCs" },
    { option1: "Slow-paced", option2: "Real-time" },
    { option1: "Customizable character", option2: "Pre-designed protagonist" },
    { option1: "Seasonal events", option2: "Daily quests" },
    { option1: "Sandbox gameplay", option2: "Story-driven" },
    { option1: "Pixelated", option2: "Low poly" },
    { option1: "Cottage core", option2: "Cyberpunk cozy" },
    { option1: "Fishing minigame", option2: "Cooking minigame" },
    { option1: "Cute pets", option2: "Magical creatures" },
    { option1: "Relaxing soundtrack", option2: "ASMR ambience" },
    { option1: "Decorating", option2: "Organizing" },
    { option1: "Plant care", option2: "Animal care" },
    { option1: "Offline mode", option2: "Online co-op" },
    { option1: "Retro-inspired", option2: "Modern indie" },
    { option1: "Handheld gaming", option2: "Desktop setup" },
    { option1: "Time management", option2: "Free-roaming" },
    { option1: "Whimsical", option2: "Realistic" },
    { option1: "Pastel colors", option2: "Earth tones" },
    { option1: "Text-based dialogue", option2: "Voice acting" },
    { option1: "Gardening", option2: "Interior design" },
    { option1: "Friendship systems", option2: "Romance options" },
    { option1: "Collect resources", option2: "Buy supplies" },
    { option1: "Day/night cycle", option2: "Always daytime" },
    { option1: "Portable game systems", option2: "Dedicated gaming PC" },
    { option1: "Casual clothing", option2: "Fancy outfits" },
    { option1: "Village life", option2: "City simulation" },
    { option1: "Pixel food", option2: "Realistic food" },
    { option1: "Procedural generation", option2: "Hand-crafted world" },
    { option1: "Changing seasons", option2: "Eternal spring" },
    { option1: "Character customization", option2: "Pre-set characters" },
    { option1: "Magical realism", option2: "Slice of life" },
    { option1: "Achievements", option2: "No pressure gaming" },
    { option1: "Mouse and keyboard", option2: "Controller" },
    { option1: "Inventory management", option2: "Infinite storage" },
    { option1: "In-game photography", option2: "Journal writing" },
    { option1: "Time travel", option2: "Real-time progression" },
    { option1: "Cozy mysteries", option2: "Peaceful exploration" },
    { option1: "Pixel art UI", option2: "Minimalist UI" },
    { option1: "Crop farming", option2: "Animal husbandry" },
    { option1: "Dungeon crawling", option2: "Town building" },
    { option1: "Lo-fi beats", option2: "Nature sounds" },
    { option1: "Nap between gaming", option2: "Snacks while gaming" },
    { option1: "Streaming cozy games", option2: "Solo quiet time" },
  ],
  forCouples: [
    { option1: "Pizza", option2: "Sushi" },
    { option1: "Early bird", option2: "Night owl" },
    { option1: "Beach vacation", option2: "Mountain getaway" },
    { option1: "Dogs", option2: "Cats" },
    { option1: "Netflix binge", option2: "Outdoor adventure" },
    { option1: "Chocolate", option2: "Vanilla" },
    { option1: "Spontaneous trips", option2: "Planned itineraries" },
    { option1: "Text", option2: "Call" },
    { option1: "Spicy food", option2: "Mild flavors" },
    { option1: "Big party", option2: "Intimate gathering" },
    { option1: "Sci-fi movies", option2: "Romance movies" },
    { option1: "Hot coffee", option2: "Iced coffee" },
    { option1: "Camping", option2: "Luxury hotel" },
    { option1: "Book", option2: "Movie" },
    { option1: "Homemade meal", option2: "Restaurant dining" },
    { option1: "Winter", option2: "Summer" },
    { option1: "Shower in the morning", option2: "Shower at night" },
    { option1: "Amusement parks", option2: "Museums" },
    { option1: "Slow dance", option2: "Wild dance moves" },
    { option1: "Board games", option2: "Video games" },
    { option1: "Breakfast in bed", option2: "Dinner under the stars" },
    { option1: "Horror movies", option2: "Comedies" },
    { option1: "Tea", option2: "Coffee" },
    { option1: "Instagram", option2: "TikTok" },
    { option1: "Save money", option2: "Splurge occasionally" },
    { option1: "Hugs", option2: "Kisses" },
    { option1: "Fancy restaurant", option2: "Cozy diner" },
    { option1: "Workout together", option2: "Solo exercise" },
    { option1: "Surprise gifts", option2: "Wishlist presents" },
    { option1: "Historical fiction", option2: "Fantasy novels" },
    { option1: "Picnic in the park", option2: "Dinner cruise" },
    { option1: "Karaoke night", option2: "Silent disco" },
    { option1: "Roller coasters", option2: "Water slides" },
    { option1: "Cooking together", option2: "Ordering takeout" },
    { option1: "Stargazing", option2: "Sunbathing" },
    { option1: "Road trip", option2: "Flying" },
    { option1: "Matching outfits", option2: "Individual styles" },
    { option1: "Brunch", option2: "Dinner date" },
    { option1: "Action movies", option2: "Documentaries" },
    { option1: "City life", option2: "Countryside living" },
    { option1: "Wine tasting", option2: "Beer sampling" },
    { option1: "Breakfast for dinner", option2: "Dinner for breakfast" },
    { option1: "Skinny dipping", option2: "Staying clothed" },
    { option1: "Couple's costume", option2: "Individual outfits" },
    { option1: "Ferris wheel", option2: "Haunted house" },
    { option1: "Candlelit bath", option2: "Couples massage" },
    { option1: "Volunteer together", option2: "Donate to charity" },
    { option1: "Grocery shopping", option2: "Online ordering" },
    { option1: "Miniature golf", option2: "Bowling" },
    { option1: "Sleeping in", option2: "Early morning cuddles" },
  ],
  work: [
    { option1: "Work from home", option2: "Work from office" },
    { option1: "Early bird", option2: "Night owl" },
    { option1: "Standing desk", option2: "Sitting desk" },
    { option1: "Coffee breaks", option2: "Power naps" },
    { option1: "Open-plan office", option2: "Private cubicles" },
    { option1: "Strict deadlines", option2: "Flexible timelines" },
    { option1: "Written communication", option2: "Verbal communication" },
    { option1: "Multitasking", option2: "Deep focus on one task" },
    { option1: "Team projects", option2: "Individual assignments" },
    { option1: "Digital notes", option2: "Handwritten notes" },
    { option1: "Morning meetings", option2: "Afternoon meetings" },
    { option1: "Casual dress code", option2: "Formal attire" },
    { option1: "Fixed work hours", option2: "Flexible schedule" },
    { option1: "Mac", option2: "PC" },
    { option1: "Google Workspace", option2: "Microsoft Office" },
    { option1: "Salary raise", option2: "More vacation days" },
    { option1: "Remote work", option2: "In-office perks" },
    { option1: "Professional development", option2: "Networking events" },
    { option1: "Mentoring others", option2: "Being mentored" },
    { option1: "Data-driven decisions", option2: "Intuition-based choices" },
    { option1: "Structured workday", option2: "Spontaneous schedule" },
    { option1: "Text messaging", option2: "Phone calls" },
    { option1: "Inbox zero", option2: "Organized chaos" },
    { option1: "Dual monitors", option2: "Single ultrawide screen" },
    { option1: "To-do lists", option2: "Calendar blocking" },
    { option1: "Pomodoro technique", option2: "Time blocking" },
    { option1: "Collaborative brainstorming", option2: "Solo ideation" },
    { option1: "Public speaking", option2: "Written reports" },
    { option1: "Constructive criticism", option2: "Positive reinforcement" },
    { option1: "Career specialization", option2: "Diverse skill set" },
    { option1: "Startup environment", option2: "Corporate structure" },
    { option1: "Fast-paced work", option2: "Methodical approach" },
    { option1: "Risk-taking projects", option2: "Steady, reliable work" },
    { option1: "Social media for work", option2: "No work on social media" },
    { option1: "Work-life balance", option2: "Career advancement" },
    { option1: "Company-wide meetings", option2: "Small team check-ins" },
    { option1: "Traditional benefits", option2: "Innovative perks" },
    { option1: "In-person networking", option2: "Online networking" },
    { option1: "Detailed project plans", option2: "Agile methodology" },
    { option1: "Regular performance reviews", option2: "Continuous feedback" },
    {
      option1: "Company-provided equipment",
      option2: "BYOD (Bring Your Own Device)",
    },
    {
      option1: "Strict information hierarchy",
      option2: "Open-book management",
    },
    { option1: "Business casual", option2: "Smart casual" },
    { option1: "Task delegation", option2: "Hands-on management" },
    { option1: "Learn new skills", option2: "Master current skills" },
    {
      option1: "Cross-functional collaboration",
      option2: "Specialized team focus",
    },
    { option1: "Work trips", option2: "Virtual conferences" },
    { option1: "Personalized workspace", option2: "Hot-desking" },
    { option1: "Results-oriented work", option2: "Process-oriented work" },
    { option1: "Quiet work environment", option2: "Background music or noise" },
  ],
  travel: [
    { option1: "Beach vacation", option2: "Mountain getaway" },
    { option1: "Hotel", option2: "Airbnb" },
    { option1: "Backpacking", option2: "Luxury resort" },
    { option1: "Planned itinerary", option2: "Spontaneous exploration" },
    { option1: "Road trip", option2: "Flight" },
    { option1: "Local cuisine", option2: "Familiar food" },
    { option1: "Group tours", option2: "Self-guided adventures" },
    { option1: "Photography", option2: "Living in the moment" },
    { option1: "Tropical destination", option2: "Arctic adventure" },
    { option1: "Historical sites", option2: "Natural wonders" },
    { option1: "Amusement parks", option2: "National parks" },
    { option1: "Cruise", option2: "Train journey" },
    { option1: "Camping", option2: "Glamping" },
    { option1: "City exploration", option2: "Rural retreat" },
    { option1: "Summer travel", option2: "Winter travel" },
    { option1: "Carry-on only", option2: "Checked luggage" },
    { option1: "Guidebooks", option2: "Local recommendations" },
    { option1: "Souvenirs", option2: "Experiences" },
    { option1: "Adventure sports", option2: "Cultural immersion" },
    { option1: "Busy tourist spots", option2: "Off-the-beaten-path" },
    { option1: "All-inclusive resort", option2: "Pay-as-you-go" },
    { option1: "Sunrise exploration", option2: "Night owl adventures" },
    {
      option1: "Foreign language immersion",
      option2: "English-speaking destinations",
    },
    { option1: "Street food", option2: "Fine dining" },
    { option1: "Hostels", option2: "Boutique hotels" },
    { option1: "Public transportation", option2: "Rental car" },
    { option1: "Day trips", option2: "Extended stays" },
    { option1: "Guided tours", option2: "Self-exploration" },
    { option1: "Travel insurance", option2: "Risk it" },
    { option1: "Packing cubes", option2: "Roll clothes" },
    { option1: "Digital maps", option2: "Physical maps" },
    { option1: "Travel vlog", option2: "Private photo album" },
    { option1: "Window seat", option2: "Aisle seat" },
    { option1: "International travel", option2: "Domestic exploration" },
    { option1: "Solo travel", option2: "Group travel" },
    { option1: "Budget airlines", option2: "Full-service carriers" },
    { option1: "Bucket list destinations", option2: "Repeat favorite spots" },
    { option1: "Adventure activities", option2: "Relaxation focus" },
    { option1: "Local markets", option2: "Shopping malls" },
    { option1: "Museums", option2: "Outdoor attractions" },
    { option1: "Volunteer travel", option2: "Leisure travel" },
    { option1: "Language apps", option2: "Phrase books" },
    { option1: "Eco-friendly options", option2: "Convenience first" },
    { option1: "Travel credit cards", option2: "Cash/debit cards" },
    { option1: "Scenic routes", option2: "Fastest routes" },
    { option1: "Passport stamps", option2: "Social media check-ins" },
    { option1: "Early booking discounts", option2: "Last-minute deals" },
    { option1: "Sightseeing", option2: "People watching" },
    { option1: "Travel light", option2: "Pack for all scenarios" },
    {
      option1: "New country every trip",
      option2: "Deep dive into one culture",
    },
    { option1: "Foodie tours", option2: "Pub crawls" },
  ],
  general: [
    { option1: "Books", option2: "Movies" },
    { option1: "Dogs", option2: "Cats" },
    { option1: "Introvert", option2: "Extrovert" },
    { option1: "Shower thoughts", option2: "Toilet epiphanies" },
    {
      option1: "Time travel to the past",
      option2: "Time travel to the future",
    },
    { option1: "Superpowers", option2: "Magic spells" },
    { option1: "Teleportation", option2: "Flying" },
    { option1: "Early bird", option2: "Night owl" },
    { option1: "Plan everything", option2: "Go with the flow" },
    { option1: "Pizza", option2: "Sushi" },
    { option1: "Netflix binge", option2: "Outdoor adventure" },
    { option1: "Text", option2: "Call" },
    { option1: "Truth", option2: "Dare" },
    { option1: "Super strength", option2: "Super intelligence" },
    { option1: "Board games", option2: "Video games" },
    { option1: "Spicy food", option2: "Sweet treats" },
    { option1: "Mountains", option2: "Beaches" },
    { option1: "Coffee", option2: "Tea" },
    { option1: "Instagram", option2: "TikTok" },
    { option1: "Save money", option2: "Spend now, worry later" },
    { option1: "Minimalist", option2: "Maximalist" },
    { option1: "Androids", option2: "iPhones" },
    { option1: "Pineapple on pizza", option2: "No pineapple on pizza" },
    { option1: "Shower in the morning", option2: "Shower at night" },
    { option1: "Use fingers as straws", option2: "Use toes as thumbs" },
    { option1: "Roommates", option2: "Live alone" },
    { option1: "Invisibility", option2: "Mind reading" },
    { option1: "Historical figures", option2: "Fictional characters" },
    { option1: "Yoga", option2: "High-intensity workouts" },
    { option1: "Camping", option2: "Luxury hotels" },
    { option1: "Spotify", option2: "Apple Music" },
    { option1: "Tattoos", option2: "Piercings" },
    { option1: "Dad jokes", option2: "Memes" },
    { option1: "Cook at home", option2: "Eat out" },
    { option1: "Sci-fi", option2: "Fantasy" },
    { option1: "Sleeping in", option2: "Productive mornings" },
    { option1: "Online shopping", option2: "In-store shopping" },
    { option1: "Skinny dip", option2: "Streak through town" },
    { option1: "Cardio", option2: "Weight lifting" },
    { option1: "Glasses", option2: "Contacts" },
    { option1: "Sunrise", option2: "Sunset" },
    { option1: "Roller coasters", option2: "Ferris wheels" },
    { option1: "Musicals", option2: "Concerts" },
    { option1: "Brunch", option2: "Dinner party" },
    { option1: "Sneakers", option2: "Dress shoes" },
    { option1: "Beer", option2: "Wine" },
    { option1: "Action movies", option2: "Rom-coms" },
    { option1: "Social media detox", option2: "24/7 connection" },
    { option1: "Picnic in the park", option2: "Fancy restaurant" },
    { option1: "Sing in public", option2: "Dance in public" },
  ],
  foodAndDrinks: [
    { option1: "Sweet", option2: "Savory" },
    { option1: "Spicy", option2: "Mild" },
    { option1: "Coffee", option2: "Tea" },
    { option1: "Chocolate", option2: "Vanilla" },
    { option1: "Burger", option2: "Pizza" },
    { option1: "Vegetarian", option2: "Meat lover" },
    { option1: "Tacos", option2: "Burritos" },
    { option1: "Sushi", option2: "Steak" },
    { option1: "Pancakes", option2: "Waffles" },
    { option1: "Wine", option2: "Beer" },
    { option1: "Smoothies", option2: "Milkshakes" },
    { option1: "Fruits", option2: "Vegetables" },
    { option1: "Fried", option2: "Grilled" },
    { option1: "Soup", option2: "Salad" },
    { option1: "Hot dog", option2: "Sandwich" },
    { option1: "Pasta", option2: "Rice" },
    { option1: "Cake", option2: "Pie" },
    { option1: "Cocktails", option2: "Mocktails" },
    { option1: "Chopsticks", option2: "Fork" },
    { option1: "Breakfast", option2: "Brunch" },
    { option1: "Thin crust", option2: "Thick crust" },
    { option1: "Crunchy", option2: "Chewy" },
    { option1: "Homemade", option2: "Restaurant" },
    { option1: "Fast food", option2: "Slow food" },
    { option1: "Hot sauce", option2: "Ketchup" },
    { option1: "Ice cream", option2: "Frozen yogurt" },
    { option1: "Sparkling water", option2: "Still water" },
    { option1: "Donuts", option2: "Bagels" },
    { option1: "Fries", option2: "Onion rings" },
    { option1: "Lemonade", option2: "Iced tea" },
    { option1: "Crispy bacon", option2: "Chewy bacon" },
    { option1: "Soft cookies", option2: "Crunchy cookies" },
    { option1: "Dark chocolate", option2: "Milk chocolate" },
    { option1: "Mayonnaise", option2: "Mustard" },
    { option1: "Pineapple on pizza", option2: "No pineapple on pizza" },
    { option1: "Rare steak", option2: "Well-done steak" },
    { option1: "Tap water", option2: "Bottled water" },
    { option1: "Energy drinks", option2: "Sports drinks" },
    { option1: "Cereal", option2: "Oatmeal" },
    { option1: "Popcorn", option2: "Chips" },
    { option1: "Hot coffee", option2: "Iced coffee" },
    { option1: "Seafood", option2: "Chicken" },
    { option1: "Coke", option2: "Pepsi" },
    { option1: "Mashed potatoes", option2: "Baked potatoes" },
    { option1: "Crispy wings", option2: "Saucy wings" },
    { option1: "Dining out", option2: "Home cooking" },
    { option1: "Food truck", option2: "Fine dining" },
    { option1: "Street food", option2: "Gourmet cuisine" },
    { option1: "Buffet", option2: "À la carte" },
    { option1: "Appetizers", option2: "Desserts" },
  ],
  forKids: [
    { option1: "Chocolate ice cream", option2: "Vanilla ice cream" },
    { option1: "Superpower of flight", option2: "Invisibility" },
    { option1: "Pizza", option2: "Tacos" },
    { option1: "Beach vacation", option2: "Mountain getaway" },
    { option1: "Video games", option2: "Board games" },
    { option1: "Cats", option2: "Dogs" },
    { option1: "Pancakes", option2: "Waffles" },
    { option1: "Summer", option2: "Winter" },
    { option1: "Reading books", option2: "Watching movies" },
    { option1: "Soccer", option2: "Basketball" },
    { option1: "Peanut butter", option2: "Jelly" },
    {
      option1: "Time travel to the past",
      option2: "Time travel to the future",
    },
    { option1: "Roller coasters", option2: "Water slides" },
    { option1: "Camping", option2: "Staying in a hotel" },
    { option1: "Dinosaurs", option2: "Dragons" },
    { option1: "Singing", option2: "Dancing" },
    { option1: "Crayons", option2: "Colored pencils" },
    { option1: "Swimming pool", option2: "Ocean" },
    { option1: "Cartoons", option2: "Live-action shows" },
    { option1: "Salty snacks", option2: "Sweet treats" },
    { option1: "Outer space", option2: "Deep sea" },
    { option1: "Talking to animals", option2: "Flying like a bird" },
    { option1: "Spaghetti", option2: "Mac and cheese" },
    { option1: "Superheroes", option2: "Villains" },
    { option1: "Building with Legos", option2: "Drawing pictures" },
    { option1: "Hugs", option2: "High-fives" },
    { option1: "Sunny days", option2: "Rainy days" },
    { option1: "Ice skating", option2: "Rollerblading" },
    { option1: "Teleportation", option2: "Mind reading" },
    { option1: "Burgers", option2: "Hot dogs" },
    { option1: "Picnic in the park", option2: "Indoor fort" },
    { option1: "Being super strong", option2: "Being super fast" },
    { option1: "Fruits", option2: "Vegetables" },
    { option1: "Snowball fights", option2: "Water balloon battles" },
    { option1: "Listening to music", option2: "Playing an instrument" },
    { option1: "Trampolines", option2: "Bounce houses" },
    { option1: "Cookies", option2: "Cupcakes" },
    { option1: "Exploring a jungle", option2: "Climbing a mountain" },
    { option1: "Robots", option2: "Magical creatures" },
    { option1: "Riding a bike", option2: "Skateboarding" },
    {
      option1: "Sandwiches cut in triangles",
      option2: "Sandwiches cut in squares",
    },
    {
      option1: "Being tiny like an ant",
      option2: "Being gigantic like a giant",
    },
    { option1: "Pillow fights", option2: "Tickle wars" },
    {
      option1: "Coloring inside the lines",
      option2: "Coloring outside the lines",
    },
    { option1: "Pirate adventures", option2: "Space exploration" },
    { option1: "Bubble wrap", option2: "Slime" },
    { option1: "Pajama day", option2: "Costume party" },
    { option1: "Chocolate milk", option2: "Fruit smoothies" },
    { option1: "Building sandcastles", option2: "Making snow forts" },
    { option1: "Magic tricks", option2: "Science experiments" },
  ],
  getToKnowYou: [
    { option1: "Pancakes", option2: "Waffles" },
    { option1: "Superhero", option2: "Supervillain" },
    { option1: "Beach vacation", option2: "Mountain retreat" },
    { option1: "Coffee", option2: "Tea" },
    { option1: "Dogs", option2: "Cats" },
    { option1: "Early bird", option2: "Night owl" },
    { option1: "Book", option2: "Movie" },
    { option1: "Invisibility", option2: "Flight" },
    { option1: "Chocolate", option2: "Vanilla" },
    { option1: "Camping", option2: "Luxury hotel" },
    { option1: "Introvert", option2: "Extrovert" },
    { option1: "Tacos", option2: "Pizza" },
    { option1: "Roller coasters", option2: "Water slides" },
    { option1: "Sci-fi", option2: "Fantasy" },
    { option1: "Sneakers", option2: "Dress shoes" },
    { option1: "Sunrise", option2: "Sunset" },
    { option1: "Spontaneous trips", option2: "Planned vacations" },
    { option1: "Spicy food", option2: "Mild flavors" },
    { option1: "Netflix binge", option2: "Outdoor adventure" },
    { option1: "Teleportation", option2: "Time travel" },
    { option1: "Text", option2: "Call" },
    { option1: "Podcast", option2: "Music playlist" },
    { option1: "Winter wonderland", option2: "Tropical paradise" },
    { option1: "Board games", option2: "Video games" },
    { option1: "Amusement park", option2: "Museum" },
    { option1: "Pineapple on pizza", option2: "No pineapple" },
    { option1: "Folding laundry", option2: "Doing dishes" },
    { option1: "Karaoke star", option2: "Silent observer" },
    { option1: "Zombie apocalypse", option2: "Alien invasion" },
    { option1: "Picnic in the park", option2: "Fancy restaurant" },
    { option1: "Swimming in the ocean", option2: "Swimming in pool" },
    { option1: "Camping in the woods", option2: "Glamping" },
    { option1: "Rollerblades", option2: "Skateboard" },
    { option1: "Mini-golf", option2: "Bowling" },
    { option1: "Acoustic guitar", option2: "Electric guitar" },
    { option1: "Historical fiction", option2: "True crime" },
    { option1: "Eating contests", option2: "Cooking shows" },
    { option1: "Superhuman strength", option2: "Superintelligence" },
    { option1: "Haunted house", option2: "Escape room" },
    { option1: "Tattoos", option2: "Piercings" },
    { option1: "Stand-up comedy", option2: "Improv show" },
    { option1: "Crossword puzzles", option2: "Sudoku" },
    { option1: "Ferris wheel", option2: "Bungee jumping" },
    { option1: "Sitcoms", option2: "Reality TV" },
    { option1: "Homemade gifts", option2: "Store-bought presents" },
    { option1: "Exploring a new city", option2: "Revisiting a favorite place" },
    { option1: "Talking animals", option2: "Talking plants" },
    { option1: "Scuba diving", option2: "Skydiving" },
    { option1: "Time freeze", option2: "Rewind button" },
    { option1: "Superspeed", option2: "Superstrength" },
  ],
  funny: [
    { option1: "Pineapple on pizza", option2: "No pineapple on pizza" },
    { option1: "Invisibility", option2: "Mind reading" },
    { option1: "Socks with sandals", option2: "Crocs with socks" },
    { option1: "Time travel to past", option2: "See the future" },
    { option1: "Always speak in rhymes", option2: "Always sing" },
    { option1: "No social media", option2: "No smartphone" },
    { option1: "Become a mermaid", option2: "Become a centaur" },
    { option1: "Smell like cheese", option2: "Always be sticky" },
    { option1: "Only eat spicy food", option2: "Only eat bland food" },
    { option1: "Laugh at funerals", option2: "Cry at weddings" },
    { option1: "Be a famous villain", option2: "Unknown hero" },
    { option1: "Hibernate 6 months", option2: "Be nocturnal" },
    { option1: "No sense of taste", option2: "No sense of smell" },
    { option1: 'Always say "yolo"', option2: 'End sentences with "bro"' },
    {
      option1: "Live in haunted mansion",
      option2: "Tiny apartment with ghosts",
    },
    { option1: "Allergic to money", option2: "Allergic to favorite food" },
    { option1: "Pet dragon", option2: "Pet unicorn" },
    { option1: "Speak all languages", option2: "Play all instruments" },
    { option1: "Never use punctuation", option2: "Always use caps lock" },
    { option1: "Read animal minds", option2: "Talk to plants" },
    { option1: "Always wear wet socks", option2: "Sand in shoes always" },
    { option1: "Famous mumble rapper", option2: "Unknown opera singer" },
    { option1: "Fingers long as legs", option2: "Legs short as fingers" },
    { option1: "Life without internet", option2: "No air conditioning" },
    { option1: "Always say wrong name", option2: "Always forget names" },
    { option1: "Sneeze glitter", option2: "Burp confetti" },
    { option1: "Silly superhero name", option2: "Cool supervillain name" },
    { option1: "Telekinesis", option2: "Telepathy" },
    { option1: "Always smell like onions", option2: "Sound like squeaky toy" },
    { option1: "Fluent in emoji", option2: "Communicate only in GIFs" },
    { option1: "Tastebuds in fingers", option2: "Eyes on back of head" },
    { option1: "Sweat maple syrup", option2: "WiFi-enabled teeth" },
    { option1: "Teleport", option2: "Fly at walking speed" },
    { option1: "Speak in third person", option2: "Always use air quotes" },
    { option1: "Personal theme song", option2: "Laugh track follows you" },
    { option1: "Immune to papercuts", option2: "Immune to brain freeze" },
    { option1: "Shapeshifting", option2: "Control elements" },
    { option1: "Always wear a onesie", option2: "Always wear formal attire" },
    {
      option1: "Read books in 5 minutes",
      option2: "Watch movies in 30 seconds",
    },
    { option1: "Photographic memory", option2: "Forget anything instantly" },
    { option1: "Speak to the dead", option2: "See the future" },
    { option1: "Irresistible to mosquitoes", option2: "Surrounded by flies" },
    { option1: "Always feel falling", option2: "Always feel floating" },
    { option1: "Have a tail", option2: "Retractable claws" },
    { option1: "Breathe underwater", option2: "Breathe in space" },
    { option1: "Shrink to 6 inches tall", option2: "Grow to 20 feet tall" },
    { option1: "Control the weather", option2: "Control time" },
    { option1: "Cursed to dad jokes", option2: "Cursed to puns" },
    { option1: "Touch turns to gold", option2: "Touch turns to chocolate" },
    { option1: "Only able to whisper", option2: "Only able to shout" },
  ],
  christmas: [
    { option1: "Real tree", option2: "Fake tree" },
    { option1: "Eggnog", option2: "Hot chocolate" },
    { option1: "Santa hat", option2: "Reindeer antlers" },
    { option1: "Christmas Eve", option2: "Christmas Day" },
    { option1: "White Christmas", option2: "Tropical Christmas" },
    { option1: "Candy canes", option2: "Gingerbread" },
    { option1: "Elf", option2: "Reindeer" },
    { option1: "Naughty list", option2: "Nice list" },
    { option1: "Christmas movies", option2: "Christmas music" },
    { option1: "Wrapping presents", option2: "Using gift bags" },
    { option1: "Tinsel", option2: "Garland" },
    { option1: "Christmas pudding", option2: "Fruit cake" },
    { option1: "Colored lights", option2: "White lights" },
    { option1: "Advent calendar", option2: "Christmas countdown app" },
    { option1: "Mistletoe", option2: "Christmas wreath" },
    { option1: "Secret Santa", option2: "White elephant" },
    { option1: "Christmas sweater", option2: "Christmas pajamas" },
    { option1: "Caroling", option2: "Christmas karaoke" },
    { option1: "Christmas market", option2: "Online shopping" },
    { option1: "Sleigh bells", option2: "Jingle bells" },
    { option1: "Christmas dinner", option2: "Christmas brunch" },
    { option1: "Star tree topper", option2: "Angel tree topper" },
    { option1: "Christmas crackers", option2: "Party poppers" },
    { option1: "Mulled wine", option2: "Spiked cider" },
    { option1: "Home Alone", option2: "Elf" },
    { option1: "Rudolph", option2: "Frosty the Snowman" },
    { option1: "Christmas cards", option2: "Holiday texts" },
    { option1: "Artificial snow", option2: "Real snow" },
    { option1: "Roasted chestnuts", option2: "Glazed ham" },
    { option1: "Indoor decorations", option2: "Outdoor decorations" },
    { option1: "Christmas socks", option2: "Christmas slippers" },
    { option1: "Scrooge", option2: "The Grinch" },
    { option1: "Volunteering", option2: "Donating to charity" },
    { option1: "Christmas village", option2: "Nativity scene" },
    { option1: "Gift giving", option2: "Gift receiving" },
    { option1: "Classic carols", option2: "Modern Christmas songs" },
    { option1: "Midnight mass", option2: "Christmas morning service" },
    { option1: "Hang stockings", option2: "Leave cookies for Santa" },
    { option1: "Fruitcake", option2: "Christmas pudding" },
    { option1: "Ugly sweater party", option2: "Formal Christmas gala" },
    { option1: "Die Hard", option2: "It's a Wonderful Life" },
    { option1: "Christmas Eve box", option2: "Christmas morning surprise" },
    { option1: "Poinsettias", option2: "Holly and ivy" },
    { option1: "Homemade ornaments", option2: "Store-bought ornaments" },
    { option1: "Christmas pickle", option2: "Christmas cracker" },
    { option1: "Eggnog latte", option2: "Peppermint mocha" },
    { option1: "Icicle lights", option2: "Net lights" },
    { option1: "The Nutcracker", option2: "A Christmas Carol" },
    { option1: "Mince pies", option2: "Pecan pie" },
    { option1: "Flocked tree", option2: "Unflocked tree" },
  ],
  spicy: [
    { option1: "Chocolate sauce", option2: "Whipped cream" },
    { option1: "Netflix and chill", option2: "Hulu and do you" },
    { option1: "Morning quickie", option2: "Late night romp" },
    { option1: "Sexy lingerie", option2: "Birthday suit" },
    { option1: "Shower together", option2: "Bubble bath for two" },
    { option1: "Public display of affection", option2: "Secret rendezvous" },
    { option1: "Dirty talk", option2: "Silent seduction" },
    { option1: "Role play", option2: "Strip tease" },
    {
      option1: "Massage with happy ending",
      option2: "Sensual dance performance",
    },
    { option1: "Blindfold", option2: "Handcuffs" },
    { option1: "Sexting", option2: "Phone sex" },
    { option1: "Beach makeout", option2: "Cozy fireplace cuddles" },
    { option1: "Naked cooking", option2: "Clothed fine dining" },
    { option1: "Surprise wake-up call", option2: "Planned date night" },
    { option1: "Truth or dare", option2: "Never have I ever" },
    { option1: "Watching adult films", option2: "Making your own video" },
    { option1: "Outdoor adventure", option2: "Indoor exploration" },
    { option1: "Slow and sensual", option2: "Fast and furious" },
    { option1: "Dominant", option2: "Submissive" },
    { option1: "Romantic getaway", option2: "Staycation with toys" },
    { option1: "Body paint", option2: "Ice cube play" },
    { option1: "Whisper sweet nothings", option2: "Scream in ecstasy" },
    { option1: "Candlelit dinner", option2: "Breakfast in bed" },
    { option1: "Mutual self-pleasure", option2: "Hands-off teasing" },
    { option1: "Skinny dipping", option2: "Hot tub party" },
    { option1: "Erotic literature", option2: "Steamy playlist" },
    { option1: "Surprise at work", option2: "Planned weekend romp" },
    { option1: "Foodplay", option2: "Body worship" },
    { option1: "Forbidden fruit roleplay", option2: "Naughty nurse scenario" },
    { option1: "Tantric techniques", option2: "Quickie in a closet" },
    { option1: "Love notes", option2: "Dirty texts" },
    { option1: "Silk sheets", option2: "Leather couch" },
    { option1: "Massage oil", option2: "Flavored lube" },
    { option1: "Striptease", option2: "Lap dance" },
    { option1: "Sexy treasure hunt", option2: "Naughty scavenger hunt" },
    { option1: "Pillow talk", option2: "Dirty talk" },
    { option1: "Romantic slow dance", option2: "Grinding on the dance floor" },
    { option1: "Edging", option2: "Multiple rounds" },
    { option1: "Couples' yoga", option2: "Naked twister" },
    { option1: "Erotic photoshoot", option2: "Boudoir sketching session" },
    { option1: "Sexy card games", option2: "Adult board games" },
    { option1: "Spontaneous car fun", option2: "Planned hotel rendezvous" },
    { option1: "Intimate truth or dare", option2: "Risqué would you rather" },
    { option1: "Sensual feeding", option2: "Body shot challenge" },
    { option1: "Sexy costume party", option2: "Naked movie night" },
    { option1: "Reading erotica together", option2: "Writing your own story" },
    { option1: "Couples' massage class", option2: "Private dance lesson" },
    { option1: "Steamy shower", option2: "Bathtub bubbles" },
    { option1: "Romantic picnic", option2: "Midnight snack in bed" },
  ],
  adultWouldYouRather: [
    { option1: "Never eat cheese again", option2: "Never eat chocolate again" },
    { option1: "Be a famous actor", option2: "Be a renowned scientist" },
    { option1: "Live in a treehouse", option2: "Live in an underwater dome" },
    { option1: "Always be overdressed", option2: "Always be underdressed" },
    {
      option1: "Time travel to the past",
      option2: "Time travel to the future",
    },
    { option1: "Read minds", option2: "Be invisible at will" },
    { option1: "Swim with sharks", option2: "Bungee jump off a cliff" },
    {
      option1: "Be fluent in all languages",
      option2: "Be a master of all instruments",
    },
    { option1: "Have a personal chef", option2: "Have a personal masseuse" },
    { option1: "Lose your phone", option2: "Lose your wallet" },
    {
      option1: "Always be 10 minutes late",
      option2: "Always be 20 minutes early",
    },
    {
      option1: "Have a photographic memory",
      option2: "Be able to forget anything",
    },
    { option1: "Live without music", option2: "Live without movies" },
    {
      option1: "Be stranded in a desert",
      option2: "Be stranded in the Arctic",
    },
    { option1: "Have many acquaintances", option2: "Have one best friend" },
    { option1: "Always say what you think", option2: "Never speak again" },
    { option1: "Be super strong", option2: "Be super flexible" },
    { option1: "Know how you'll die", option2: "Know when you'll die" },
    { option1: "Be a dragon", option2: "Ride a dragon" },
    { option1: "Have telekinesis", option2: "Have telepathy" },
    { option1: "Never need to sleep", option2: "Never need to eat" },
    { option1: "Be Batman", option2: "Be Iron Man" },
    { option1: "Win the lottery", option2: "Find your soulmate" },
    { option1: "Have X-ray vision", option2: "Have night vision" },
    { option1: "Control fire", option2: "Control water" },
    { option1: "Be a vampire", option2: "Be a werewolf" },
    { option1: "Speak to animals", option2: "Speak to the dead" },
    { option1: "Have unlimited money", option2: "Have unlimited time" },
    { option1: "Be a famous singer", option2: "Be a famous athlete" },
    { option1: "Live in virtual reality", option2: "Live in the real world" },
    {
      option1: "Have a rewind button",
      option2: "Have a pause button for life",
    },
    { option1: "Be able to fly", option2: "Be able to teleport" },
    { option1: "Always be cold", option2: "Always be hot" },
    { option1: "Have a unicorn", option2: "Have a pegasus" },
    { option1: "Never age physically", option2: "Never age mentally" },
    {
      option1: "Be the funniest person alive",
      option2: "Be the smartest person alive",
    },
    { option1: "Have 3 arms", option2: "Have 3 legs" },
    {
      option1: "Live without the internet",
      option2: "Live without electricity",
    },
    { option1: "Be a superhero", option2: "Be a supervillain" },
    {
      option1: "Explore the depths of the ocean",
      option2: "Explore the surface of Mars",
    },
    {
      option1: "Have the ability to shapeshift",
      option2: "Have the ability to clone yourself",
    },
    { option1: "Be irresistible to all", option2: "Be invisible to all" },
    { option1: "Know every language", option2: "Know every instrument" },
    {
      option1: "Fight 100 duck-sized horses",
      option2: "Fight 1 horse-sized duck",
    },
    {
      option1: "Always speak in rhymes",
      option2: "Always sing instead of speak",
    },
    { option1: "Have a third eye", option2: "Have a sixth sense" },
    {
      option1: "Be a famous YouTuber",
      option2: "Be a successful entrepreneur",
    },
    { option1: "Live in a big city", option2: "Live in the countryside" },
    { option1: "Have infinite battery life", option2: "Have infinite data" },
  ],
  toAskYourGirlfriend: [
    { option1: "Netflix", option2: "Going out" },
    { option1: "Beach vacation", option2: "Mountain getaway" },
    { option1: "Spontaneous date", option2: "Planned romantic evening" },
    { option1: "Cooking together", option2: "Ordering takeout" },
    { option1: "Early bird", option2: "Night owl" },
    { option1: "Chocolate", option2: "Vanilla" },
    { option1: "Cuddling", option2: "Making out" },
    { option1: "Homebody", option2: "Adventure seeker" },
    { option1: "Texts", option2: "Phone calls" },
    { option1: "Big wedding", option2: "Intimate ceremony" },
    { option1: "Dogs", option2: "Cats" },
    { option1: "Summer", option2: "Winter" },
    { option1: "Reading", option2: "Watching movies" },
    { option1: "City life", option2: "Countryside living" },
    { option1: "Breakfast in bed", option2: "Dinner under the stars" },
    { option1: "Tattoos", option2: "Piercings" },
    { option1: "Saving money", option2: "Splurging occasionally" },
    { option1: "Homemade gifts", option2: "Store-bought presents" },
    { option1: "Social butterfly", option2: "Introvert" },
    { option1: "Fitness enthusiast", option2: "Couch potato" },
    { option1: "Wine", option2: "Beer" },
    { option1: "Romantic comedy", option2: "Action movie" },
    { option1: "Instagram", option2: "TikTok" },
    { option1: "Road trip", option2: "Flying" },
    { option1: "Vegetarian", option2: "Meat lover" },
    { option1: "Surprise gifts", option2: "Choosing together" },
    { option1: "Coffee", option2: "Tea" },
    { option1: "Outdoorsy", option2: "Indoor activities" },
    { option1: "Dancing", option2: "Karaoke" },
    { option1: "Fancy restaurant", option2: "Street food" },
    { option1: "Matching outfits", option2: "Individual style" },
    { option1: "Board games", option2: "Video games" },
    { option1: "Spa day", option2: "Adrenaline rush" },
    { option1: "Hot tub", option2: "Swimming pool" },
    { option1: "Concerts", option2: "Theater performances" },
    { option1: "Roses", option2: "Wildflowers" },
    { option1: "Camping", option2: "Luxury hotel" },
    { option1: "Wearing makeup", option2: "Natural look" },
    { option1: "Shower", option2: "Bath" },
    { option1: "Holding hands", option2: "Arm around shoulder" },
    { option1: "Sunrise", option2: "Sunset" },
    { option1: "Spicy food", option2: "Mild flavors" },
    { option1: "Roller coasters", option2: "Ferris wheels" },
    { option1: "Sci-fi", option2: "Fantasy" },
    { option1: "Dressing up", option2: "Casual wear" },
    { option1: "Sweet", option2: "Savory" },
    { option1: "Texting all day", option2: "One long call" },
    { option1: "Partying", option2: "Quiet night in" },
    { option1: "Superhero movies", option2: "Rom-coms" },
    { option1: "Planned trips", option2: "Spontaneous adventures" },
  ],
  toAskYourBoyfriend: [
    { option1: "Netflix and chill", option2: "Adventure outdoors" },
    { option1: "Early bird", option2: "Night owl" },
    { option1: "Spontaneous trips", option2: "Planned vacations" },
    { option1: "Dogs", option2: "Cats" },
    { option1: "Texting", option2: "Calling" },
    { option1: "Beach", option2: "Mountains" },
    { option1: "Homemade meals", option2: "Eating out" },
    { option1: "Sci-fi movies", option2: "Rom-coms" },
    { option1: "Video games", option2: "Board games" },
    { option1: "Introvert", option2: "Extrovert" },
    { option1: "Shower in the morning", option2: "Shower at night" },
    { option1: "Coffee", option2: "Tea" },
    { option1: "Book smarts", option2: "Street smarts" },
    { option1: "Saving money", option2: "Spending on experiences" },
    { option1: "Optimist", option2: "Realist" },
    { option1: "Camping", option2: "Luxury hotel" },
    { option1: "Tattoos", option2: "No tattoos" },
    { option1: "Instagram", option2: "TikTok" },
    { option1: "Big party", option2: "Intimate gathering" },
    { option1: "Sports fan", option2: "Music enthusiast" },
    { option1: "Summer", option2: "Winter" },
    { option1: "Cooking together", option2: "Ordering takeout" },
    { option1: "Action movies", option2: "Comedy shows" },
    { option1: "City life", option2: "Countryside living" },
    { option1: "Reading a book", option2: "Watching a movie" },
    { option1: "Pizza", option2: "Sushi" },
    { option1: "Gym workout", option2: "Outdoor exercise" },
    { option1: "Chocolate", option2: "Vanilla" },
    { option1: "Playing sports", option2: "Watching sports" },
    { option1: "Beer", option2: "Wine" },
    { option1: "Fancy restaurant", option2: "Food truck" },
    { option1: "Rollercoasters", option2: "Ferris wheels" },
    { option1: "Sunrise", option2: "Sunset" },
    { option1: "Pineapple on pizza", option2: "No pineapple on pizza" },
    { option1: "Skinny dipping", option2: "Stargazing" },
    { option1: "Road trip", option2: "Flying" },
    { option1: "Boxers", option2: "Briefs" },
    { option1: "Dancing", option2: "Karaoke" },
    { option1: "Horror movies", option2: "Feel-good films" },
    { option1: "Beard", option2: "Clean-shaven" },
    { option1: "Cuddling", option2: "Making out" },
    { option1: "Instagram stories", option2: "Snapchat" },
    { option1: "Superhero movies", option2: "Documentaries" },
    { option1: "Concerts", option2: "Music festivals" },
    { option1: "Amusement parks", option2: "Museums" },
    { option1: "Twitter", option2: "Facebook" },
    { option1: "Matching outfits", option2: "Individual style" },
    { option1: "Hiking", option2: "Biking" },
    { option1: "Breakfast in bed", option2: "Picnic in the park" },
    { option1: "Xbox", option2: "PlayStation" },
    { option1: "Skydiving", option2: "Bungee jumping" },
  ],
  weird: [
    { option1: "Read minds", option2: "Control dreams" },
    { option1: "Always be naked", option2: "Always wear a spacesuit" },
    { option1: "Speak to animals", option2: "Speak to the dead" },
    { option1: "Taste music", option2: "See sounds" },
    { option1: "Never sleep", option2: "Never speak" },
    { option1: "Live underwater", option2: "Live in outer space" },
    {
      option1: "Immortal but always itchy",
      option2: "Mortal but always comfy",
    },
    {
      option1: "Time travel to the past",
      option2: "Time travel to the future",
    },
    { option1: "Teleport randomly daily", option2: "Fly but only 3 feet high" },
    {
      option1: "Shapeshift into any animal",
      option2: "Transform into any object",
    },
    { option1: "Always tell the truth", option2: "Always lie convincingly" },
    { option1: "Super strength", option2: "Super intelligence" },
    {
      option1: "Invisible but smell bad",
      option2: "Visible but smell amazing",
    },
    { option1: "Control weather", option2: "Control emotions" },
    { option1: "Eat anything once", option2: "Eat one thing forever" },
    { option1: "Cry money", option2: "Sweat honey" },
    {
      option1: "Read fast, forget quickly",
      option2: "Read slow, remember forever",
    },
    { option1: "Reverse aging", option2: "Stop aging" },
    { option1: "Always be too hot", option2: "Always be too cold" },
    { option1: "Breathe underwater", option2: "Survive in space" },
    { option1: "Never lose", option2: "Never win" },
    { option1: "Live without internet", option2: "Live without electricity" },
    { option1: "Always be late", option2: "Always be early" },
    { option1: "Laugh money", option2: "Sneeze confetti" },
    { option1: "Be a famous actor", option2: "Be an anonymous hero" },
    { option1: "Speak all languages", option2: "Play all instruments" },
    { option1: "Always sing", option2: "Always dance" },
    { option1: "Shoot spaghetti from hands", option2: "Midas touch (gold)" },
    { option1: "Be a vampire", option2: "Be a werewolf" },
    {
      option1: "Travel to fictional worlds",
      option2: "Bring fiction to reality",
    },
    { option1: "Know how you'll die", option2: "Know when you'll die" },
    { option1: "Read thoughts", option2: "Erase memories" },
    { option1: "Telekinesis", option2: "Telepathy" },
    { option1: "X-ray vision", option2: "Night vision" },
    { option1: "Super speed", option2: "Super strength" },
    { option1: "Live in the past", option2: "Live in the future" },
    { option1: "Be a dragon", option2: "Be a unicorn" },
    { option1: "Ability to fly", option2: "Ability to teleport" },
    { option1: "Shrink to ant size", option2: "Grow to giant size" },
    { option1: "Restart life at any age", option2: "Pause life at any age" },
    { option1: "Time stop", option2: "Time acceleration" },
    { option1: "Talk to plants", option2: "Command insects" },
    { option1: "Photographic memory", option2: "Ability to forget at will" },
    { option1: "Be a ghost", option2: "Be a zombie" },
    { option1: "Breathe fire", option2: "Control water" },
    { option1: "Always float", option2: "Always bounce" },
    { option1: "Eat anything without harm", option2: "Never need to eat" },
    { option1: "Live in a video game", option2: "Live in a book world" },
  ],
  productHunt: [
    { option1: "MVP", option2: "Fully-featured launch" },
    { option1: "Bootstrapped", option2: "VC-funded" },
    { option1: "Open source", option2: "Proprietary" },
    { option1: "Freemium model", option2: "Paid from day one" },
    { option1: "Mobile-first", option2: "Web-first" },
    { option1: "B2B focus", option2: "B2C focus" },
    { option1: "AI-powered products", option2: "Human-centric tools" },
    { option1: "No-code tools", option2: "Traditional development" },
    { option1: "Growth hacking", option2: "Organic growth" },
    { option1: "Product-led growth", option2: "Sales-led growth" },
    { option1: "Stealth mode launch", option2: "Public beta testing" },
    { option1: "Daily active users", option2: "Monthly active users" },
    { option1: "User feedback", option2: "Data-driven decisions" },
    { option1: "Design-centric", option2: "Feature-centric" },
    { option1: "Remote-first tools", option2: "Office collaboration tools" },
    { option1: "Chrome extensions", option2: "Standalone apps" },
    { option1: "iOS", option2: "Android" },
    { option1: "Subscription model", option2: "One-time purchase" },
    { option1: "Social media marketing", option2: "Content marketing" },
    { option1: "Email outreach", option2: "Cold calling" },
    { option1: "ProductHunt launch", option2: "TechCrunch feature" },
    { option1: "Hackathon projects", option2: "Long-term development" },
    { option1: "User onboarding", option2: "Feature tutorials" },
    { option1: "Slack communities", option2: "Discord servers" },
    { option1: "Trello", option2: "Asana" },
    { option1: "Figma", option2: "Sketch" },
    { option1: "GitHub", option2: "GitLab" },
    { option1: "Notion", option2: "Evernote" },
    { option1: "Zapier", option2: "IFTTT" },
    { option1: "Airtable", option2: "Google Sheets" },
    { option1: "Webflow", option2: "WordPress" },
    { option1: "Stripe", option2: "PayPal" },
    { option1: "Intercom", option2: "Zendesk" },
    { option1: "Mailchimp", option2: "ConvertKit" },
    { option1: "Canva", option2: "Adobe Creative Suite" },
    { option1: "Zoom", option2: "Google Meet" },
    { option1: "Typeform", option2: "Google Forms" },
    { option1: "Bubble", option2: "Webflow" },
    { option1: "Shopify", option2: "WooCommerce" },
    { option1: "Substack", option2: "Medium" },
    { option1: "Buffer", option2: "Hootsuite" },
    { option1: "Calendly", option2: "Doodle" },
    { option1: "Loom", option2: "Zoom" },
    { option1: "Pitch", option2: "Slidebean" },
    { option1: "Framer", option2: "InVision" },
    { option1: "Miro", option2: "Figjam" },
    { option1: "Clubhouse", option2: "Twitter Spaces" },
    { option1: "Product demos", option2: "Written case studies" },
    { option1: "KPIs", option2: "OKRs" },
    { option1: "A/B testing", option2: "Multivariate testing" },
    { option1: "Customer interviews", option2: "Surveys" },
    { option1: "Agile", option2: "Waterfall" },
  ],
};
